Repository AY2324S1-CS2103T-W09-1/tp, pull requests merged in 2023-11, with the labels that each got.

#121 Update UG with model (AddCommand)
  docs/UserGuide.md
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#125 Clone update (To allow cloning a person more than once)
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CloneCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, enhancement

#127 Update UG with AddCommand details (Changes to example format)
  docs/UserGuide.md
  docs/images/addduplicateparam.png
  docs/images/addinvalidemail.png
  docs/images/addmissingparam.png
Labels: documentation

#130 Update add ug
  docs/UserGuide.md
Labels: documentation

#137 Update ug sort
  docs/UserGuide.md
Labels: documentation

#136 Update ug calendar
  docs/UserGuide.md
  docs/images/calendarWindow.png
Labels: documentation

#126 Update clone ug
  docs/UserGuide.md
  docs/images/clonesuffixerror.png
Labels: documentation

#135 Calendar util test
  src/main/java/seedu/address/commons/util/CalendarUtil.java
  src/test/java/seedu/address/commons/util/CalendarUtilTest.java
Labels: testing

#141 Calendarwindow abstraction
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: type.Task

#145 Update User Guide
  docs/UserGuide.md
  docs/images/helpFormat.png
  docs/images/invalidRiskProfile1.png
  docs/images/invalidRiskProfile2.png
  docs/images/listFormat.png
  docs/images/questionnaireFormat.png
  docs/images/questionnaireResult.png
  docs/images/questionnaireWindow.png
  docs/images/riskProfileFormat.png
  docs/images/riskProfileResult.png
Labels: documentation

#111 Update UG with enhanced delete
  docs/UserGuide.md
  docs/images/delete-UG/after_delete_failure.png
  docs/images/delete-UG/after_delete_success.png
  docs/images/delete-UG/deleteafter.png
  docs/images/delete-UG/deleteformat.png
  docs/images/delete-UG/deletenoindex.png
  docs/images/delete-UG/deletewrongindex.png
Labels: documentation

#148 Update ug edit
  docs/UserGuide.md
  docs/images/edit-UG/editfailure.png
  docs/images/edit-UG/editformat.png
  docs/images/edit-UG/editresult.png
Labels: documentation

#151 Update ug edit v2
  docs/UserGuide.md
  docs/images/edit-UG/editfailure.png
  docs/images/edit-UG/editformat.png
  docs/images/edit-UG/editresult.png
Labels: documentation

#154 Redo UG
  docs/UserGuide.md
  docs/images/redo-UG/add_person.png
  docs/images/redo-UG/redo_failure.png
  docs/images/redo-UG/redo_success.png
  docs/images/redo-UG/undo_after_redo.png
  docs/images/redo-UG/undo_success.png
Labels: documentation

#153 Redo
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
Labels: enhancement

#155 Fix delete bug where error when duplicate indexes
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: bug

#202 Fix issue 184
  docs/UserGuide.md
Labels: documentation

#203 Fix issue 196
  docs/UserGuide.md
Labels: documentation

#209 Fix issue 177
  docs/UserGuide.md
Labels: severity.Medium, feature flaw, ug bugs

#206 Fix #186, #194 and #195
  docs/UserGuide.md
  docs/images/cloneformat.png
  docs/images/cloneresult.png
Labels: bug

#205 Fix Issue #160, #162, #171, #182
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: bug

#204 Fix issue #201
  docs/UserGuide.md
Labels: feature flaw, ug bugs

#211 Fix issue 178,198
  docs/UserGuide.md
  docs/images/calendar-UG/calendarWindow.png
  docs/images/calendarWindow.png
  docs/images/sort-UG/sortfailuremissing.png
  docs/images/sort-UG/sortformat.png
  docs/images/sort-UG/sortresult.png
Labels: severity.Low, functionality bugs, ug bugs

#210 Fix issue 190,191,197
  docs/UserGuide.md
Labels: severity.VeryLow, feature flaw, ug bugs

#221 Fix undo bug, Issue #193
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#213 Add content to table of content
  docs/UserGuide.md
Labels: ug bugs

#212 Fix #200, #192, #189, #183, #161, #157
  docs/UserGuide.md
Labels: feature flaw, ug bugs

#224 Fix issue 185
  docs/UserGuide.md
Labels: feature flaw, ug bugs

#223 Fix #174
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: ug bugs

#225 Update the FAQ
  docs/UserGuide.md
Labels: documentation

#228 Update UG
  docs/UserGuide.md
  docs/images/add-UG/add_success.png
  docs/images/add-UG/addduplicateparam.png
  docs/images/add-UG/addformat.png
  docs/images/add-UG/addinvalidemail.png
  docs/images/add-UG/addmissingparam.png
  docs/images/addresult.png
  docs/images/calendar-UG/cal0.png
  docs/images/calendar-UG/cal1.png
  docs/images/calendar-UG/cal2.png
  docs/images/clone-UG/clone_success.png
  docs/images/clone-UG/clonebeforeerror.png
  docs/images/clone-UG/cloneformat.png
  docs/images/clone-UG/cloneinvalidindex.png
  docs/images/clone-UG/clonelargeindex.png
  docs/images/clone-UG/cloneresult.png
  docs/images/clone-UG/clonesuffixerror.png
  docs/images/delete-UG/deleteformat.png
  docs/images/edit-UG/editfailure.png
  docs/images/edit-UG/editformat.png
  docs/images/find-UG/find1.png
  docs/images/find-UG/find2.png
  docs/images/find-UG/find_a0.png
  docs/images/find-UG/find_a1.png
  docs/images/find-UG/find_a2.png
  docs/images/find-UG/find_appt0.png
  docs/images/find-UG/find_appt1.png
  docs/images/find-UG/find_appt2.png
  docs/images/find-UG/find_appt3.png
  docs/images/find-UG/find_appt4.png
  docs/images/find-UG/find_n0.png
  docs/images/find-UG/find_n1.png
  docs/images/find-UG/find_n2.png
  docs/images/find-UG/findadd0.png
  docs/images/find-UG/findadd1.png
  docs/images/find-UG/findadd2.png
  docs/images/findAlexDavidResult.png
  docs/images/help-UG/helpMessage.png
  docs/images/help-UG/helpWindow.png
  docs/images/help-UG/help_success.png
  docs/images/helpFormat.png
  docs/images/list-UG/listFormat.png
  docs/images/list-UG/listResult.png
  docs/images/questionnaire-UG/invalidRiskProfile1.png
  docs/images/questionnaire-UG/invalidRiskProfile2.png
  docs/images/questionnaire-UG/questionnaireFormat.png
  docs/images/questionnaire-UG/questionnaireResult.png
  docs/images/questionnaire-UG/questionnaireWindow.png
  docs/images/questionnaire-UG/questionnaire_success.png
  docs/images/riskProfile-UG/riskProfileFormat.png
  docs/images/riskProfile-UG/riskProfileResult.png
Labels: documentation

#227 Update clone dg
  docs/DeveloperGuide.md
  docs/diagrams/CloneActivityDiagram.puml
  docs/diagrams/CloneActivityDiagram0.puml
  docs/diagrams/CloneActivityDiagram1.puml
  docs/diagrams/CloneActivityDiagram2.puml
  docs/images/CloneActivityDiagram.png
  docs/images/CloneActivityDiagram0.png
  docs/images/CloneActivityDiagram1.png
  docs/images/CloneActivityDiagram2.png
Labels: documentation

#232 Update DG for "find" command
  docs/DeveloperGuide.md
  docs/diagrams/FindAddActivityDiagram.puml
  docs/diagrams/FindApptActivityDiagram.puml
  docs/diagrams/FindNameActivityDiagram.puml
  docs/images/FindAddActivityDiagram.png
  docs/images/FindApptActivityDiagram.png
  docs/images/FindNameActivityDiagram.png
Labels: documentation

#229 Fix calendar navigation bug
  docs/UserGuide.md
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: bug, functionality bugs

#234 Update ug v3
  docs/UserGuide.md
  docs/images/Ui.png
  docs/team/syamfarh.md
Labels: documentation

#207 Update PPP (Bhanuka)
  docs/team/bhnuka.md
Labels: documentation

#236 Updates Add, Clone and Delete in UG to be more user centric.
  docs/UserGuide.md
  docs/images/add-UG/add_success.png
  docs/images/add-UG/addbefore.png
  docs/images/clone-UG/clonebefore.png
Labels: documentation

#230 Update DG (Appendixes)
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#237 Update PPP - Glenn
  docs/team/glenngnng.md
Labels: documentation

#233 Update DG (Delete)
  docs/DeveloperGuide.md
  docs/diagrams/Delete0.puml
  docs/diagrams/Delete1.puml
  docs/diagrams/DeleteActivityDiagram0.puml
  docs/diagrams/DeleteActivityDiagram1.puml
  docs/images/Delete0.png
  docs/images/Delete1.png
  docs/images/DeleteActivityDiagram0.png
  docs/images/DeleteActivityDiagram1.png
Labels: documentation

#238 Update PPP (Daphne)
  docs/team/daphne789.md
Labels: documentation

#239 Update DG: help, questionnaire, riskprofile, list, and exit features
  docs/DeveloperGuide.md
  docs/diagrams/FinalAddressBook.puml
  docs/diagrams/InitialAddressBook.puml
  docs/diagrams/RiskProfileClass.puml
  docs/diagrams/RiskProfileParserClass.puml
  docs/diagrams/RiskProfileSequenceDiagram.puml
  docs/images/FinalAddressBook.png
  docs/images/InitialAddressBook.png
  docs/images/RiskProfileCommandClass.png
  docs/images/RiskProfileCommandParserClass.png
  docs/images/RiskProfileSequenceDiagram.png
Labels: documentation

#235 Update DG for Undo and Redo
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/AddressBookState.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagramForUndo.puml
  docs/diagrams/ModelManager.puml
  docs/diagrams/ModelManagerArrayLists.puml
  docs/diagrams/ModelManagerArrayLists0.puml
  docs/diagrams/ModelManagerArrayLists1.puml
  docs/diagrams/RedoSequenceDiagram.puml
  docs/diagrams/UndoSequenceDiagram1.puml
  docs/diagrams/UndoSequenceDiagram2.puml
  docs/diagrams/UndoSequenceDiagramForDelete.puml
  docs/images/AddressBookState1.png
  docs/images/AddressBookState2.png
  docs/images/DeleteSequenceDiagramForUndo.png
  docs/images/ModelManagerStateDiagram0.png
  docs/images/ModelManagerStateDiagram1.png
  docs/images/ModelManagerStateDiagram2.png
  docs/images/ModelManagerStateDiagram3.png
  docs/images/ModelManagerStateDiagram4.png
  docs/images/ModelManagerStateDiagram5.png
  docs/images/ModelManagerStateDiagram6.png
  docs/images/RedoSequenceDiagram.png
  docs/images/UndoSequenceDiagram1.png
  docs/images/UndoSequenceDiagram2.png
  docs/images/UndoSequenceDiagramForDelete.png
  src/main/java/seedu/address/logic/commands/UndoCommand.java
Labels: documentation

#240 Update ug minor fixes
  docs/UserGuide.md
Labels: documentation

#241 Update dg calendar implementation
  docs/DeveloperGuide.md
  docs/diagrams/Sort1.puml
  docs/diagrams/SortActivityDiagram.puml
  docs/images/Sort1.png
  docs/images/SortActivityDiagram.png
Labels: documentation

#248 Update dg final final
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: documentation

#250 Update DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/bhnuka.md
Labels: documentation

#251 Update UG to use user-centric style
  docs/UserGuide.md
Labels: documentation

#249 Update DG with AddCommand
  docs/DeveloperGuide.md
  docs/diagrams/Add0.puml
  docs/diagrams/Add1.puml
  docs/diagrams/AddActivityDiagram0.puml
  docs/diagrams/AddActivityDiagram1.puml
  docs/images/AddActivityDiagram0.png
  docs/images/AddActivityDiagram1.png
  docs/images/add0.png
  docs/images/add1.png
Labels: documentation

#252 Improve code quality
  src/main/java/seedu/address/commons/util/CalendarUtil.java
  src/main/java/seedu/address/logic/parser/DateTimeParser.java
  src/main/java/seedu/address/ui/CalendarWindow.java
Labels: documentation

#254 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/HelpActivityDiagram.puml
  docs/diagrams/RiskProfileActivityDiagram.puml
  docs/diagrams/RiskProfileClass.puml
  docs/images/HelpActivityDiagram.png
  docs/images/RiskProfileActivityDiagram.png
  docs/images/RiskProfileCommandClass.png
Labels: documentation

#253 Fix code quality
  docs/UserGuide.md
Labels: documentation

#255 UG Redo screenshots
  docs/UserGuide.md
  docs/images/redo-UG/redo-example/AfterAddingJohn.png
  docs/images/redo-UG/redo-example/AfterDeleteJohn.png
  docs/images/redo-UG/redo-example/AfterRedoingUndoJohnIsBack.png
  docs/images/redo-UG/redo-example/AfterUndoingAddJohn.png
  docs/images/redo-UG/redo-example/AfterUndoingDeleteJohn.png
  docs/images/redo-UG/redo-example/AfterUndoingRedoJohnIsGone.png
  docs/images/redo-UG/redo-example/BeforeDeleteJohn.png
  docs/images/redo-UG/redo-example/EmptyBeforeAddingJohn.png
  docs/images/redo-UG/redo-example/NothingToUndo.png
  docs/images/redo-UG/redo-example/StartAppWith1ContactJohn.png
Labels: documentation

#256 Update DG planned enhancements + manual test cases
  docs/DeveloperGuide.md
Labels: documentation

#259 Edit NFR
  docs/DeveloperGuide.md
Labels: documentation

#262 Update the help window image
  docs/images/help-UG/helpWindow.png
Labels: documentation

#270 Update PPP
  docs/DeveloperGuide.md
  docs/team/glenngnng.md
Labels: documentation

#268 Update Clone1 for consistency
  docs/DeveloperGuide.md
  docs/diagrams/Clone1.puml
  docs/images/Clone1.png
Labels: documentation

#272 Update PPP
  docs/team/glenngnng.md
Labels: documentation

#280 Crop images in UG
  docs/UserGuide.md
  docs/images/add-UG/addduplicateparam.png
  docs/images/add-UG/addinvalidemail.png
  docs/images/add-UG/addmissingparam.png
  docs/images/clear-UG/clear_failure.png
  docs/images/clone-UG/cloneinvalidindex.png
  docs/images/clone-UG/clonelargeindex.png
  docs/images/clone-UG/clonesuffixerror.png
  docs/images/delete-UG/deletenoindex.png
  docs/images/delete-UG/deletewrongindex.png
  docs/images/edit-UG/editfailure.png
  docs/images/edit-UG/editformat.png
  docs/images/edit-UG/editresult.png
  docs/images/find-UG/find_a2.png
  docs/images/find-UG/find_appt2.png
  docs/images/find-UG/find_appt3.png
  docs/images/find-UG/find_appt4.png
  docs/images/find-UG/find_n2.png
  docs/images/redo-UG/add_person.png
  docs/images/redo-UG/redo-example/AfterAddingJohn.png
  docs/images/redo-UG/redo-example/AfterDeleteJohn.png
  docs/images/redo-UG/redo-example/AfterRedoingUndoJohnIsBack.png
  docs/images/redo-UG/redo-example/AfterUndoingAddJohn.png
  docs/images/redo-UG/redo-example/AfterUndoingDeleteJohn.png
  docs/images/redo-UG/redo-example/AfterUndoingRedoJohnIsGone.png
  docs/images/redo-UG/redo-example/EmptyBeforeAddingJohn.png
  docs/images/redo-UG/redo-example/NothingToUndo.png
  docs/images/redo-UG/redo_failure.png
  docs/images/redo-UG/redo_success.png
  docs/images/redo-UG/undo_after_redo.png
  docs/images/redo-UG/undo_success.png
  docs/images/riskProfile-UG/invalidRiskProfile1.png
  docs/images/riskProfile-UG/invalidRiskProfile2.png
  docs/images/riskProfile-UG/invalidRiskProfile3.png
  docs/images/sort-UG/sortfailuremissing.png
  docs/images/undo-UG/after_add.png
  docs/images/undo-UG/after_add_undo.png
  docs/images/undo-UG/after_clone_1.png
  docs/images/undo-UG/after_clone_undo.png
  docs/images/undo-UG/after_delete_1.png
  docs/images/undo-UG/after_delete_undo.png
  docs/images/undo-UG/after_edit.png
  docs/images/undo-UG/after_edit_undo.png
  docs/images/undo-UG/undo_fail.png
Labels: documentation

#281 Ug finalfinal
  docs/UserGuide.md
  docs/team/syamfarh.md
Labels: documentation

#283 Change image name in UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/questionnaire-UG/questionnaireWindow.png
Labels: documentation
