Repository AY2324S1-CS2103T-W09-1/tp, pull requests merged in 2023-10, with the labels that each got.

#17 Add skeletal PPP, glenngnng.md
  docs/team/glenngnng.md
Labels: documentation

#24 Update PPP for syamfarh
  docs/team/syamfarh.md
Labels: documentation

#28 Add Skeletal for Daphne's Project Portfolio Page
  docs/team/daphne789.md
Labels: documentation

#39 Update user guide
  docs/UserGuide.md
  docs/images/deleteformat.png
  docs/images/deleteresult.png
Labels: documentation

#42 Update the User Guide for Help Feature
  docs/UserGuide.md
  docs/images/helpWindow.png
Labels: documentation

#46 Remove references to AB3 and touched up on some formatting (to inclu…
  docs/UserGuide.md
Labels: documentation

#43 Update Use Cases in the Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#49 Update with occupation
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Occupation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/OccupationTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.Enhancement, priority.High

#50 Modify the help window
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: enhancement, type.Enhancement, priority.High

#52 Bug fix edit command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug

#54 Appt date param
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DateParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/AppointmentDate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/DateParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AppointmentDateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Story

#58 Update HelpWindow
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: enhancement, priority.High

#59 Update user guide for help command
  docs/UserGuide.md
  docs/images/helpWindow.png
Labels: documentation

#65 Update GUI
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/fapro.png
  src/main/resources/view/DefaultTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: enhancement, priority.Medium

#68 Enable assertions in build.gradle
  build.gradle
Labels: documentation, priority.High

#78 Update PPP (bhnuka)
  docs/team/bhnuka.md
Labels: documentation

#79 Update CloneCommand to throw exception
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/test/java/seedu/address/logic/commands/CloneCommandTest.java
Labels: enhancement

#71 Undo more deletions, clear, add, edit
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: enhancement

#85 Modify the content of the Help Window
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Enhancement

#73 Update UG CloneCommand
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/clonebeforeerror.png
  docs/images/cloneformat.png
  docs/images/cloneinvalidindex.png
  docs/images/clonelargeindex.png
  docs/images/cloneresult.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CloneCommand.java
Labels: documentation

#74 Update UG AddCommand
  docs/UserGuide.md
  docs/images/addduplicateparam.png
  docs/images/addformat.png
  docs/images/addinvalidemail.png
  docs/images/addmissingparam.png
  docs/images/addresult.png
Labels: documentation

#72 Update DG CloneCommand
  docs/DeveloperGuide.md
  docs/diagrams/Clone0.puml
  docs/diagrams/Clone1.puml
  docs/diagrams/CloneActivityDiagram.puml
  docs/images/Clone0.png
  docs/images/Clone1.png
  docs/images/CloneActivityDiagram.png
Labels: documentation

#90 Update UG ClearCommand
  docs/UserGuide.md
  docs/images/clear-UG/clear_failure.png
  docs/images/clear-UG/clear_success.png
Labels: documentation

#84 Update DG to include find command
  docs/DeveloperGuide.md
Labels: documentation

#91 Remove extra input
  docs/DeveloperGuide.md
Labels: documentation

#94 Modify Developer Guide for help feature
  docs/DeveloperGuide.md
Labels: documentation

#92 Update DG UndoCommand
  docs/DeveloperGuide.md
Labels: documentation

#95 Modify the User Guide for help, list, and exit features
  docs/UserGuide.md
  docs/images/helpWindow.png
  docs/images/listResult.png
Labels: documentation

#88 Update UG DeleteCommand
  docs/UserGuide.md
  docs/images/delete-UG/after_delete_failure.png
  docs/images/delete-UG/after_delete_success.png
  docs/images/delete-UG/deleteformat.png
  docs/images/deleteformat.png
  docs/images/deleteresult.png
Labels: documentation

#86 Update UG UndoCommand
  docs/UserGuide.md
  docs/images/undo-UG/after_add_scrolled_down.png
  docs/images/undo-UG/after_add_undo_scrolled_down.png
  docs/images/undo-UG/after_clear.png
  docs/images/undo-UG/after_clear_undo.png
  docs/images/undo-UG/after_clone_1_scrolled_down.png
  docs/images/undo-UG/after_clone_undo_scrolled_down.png
  docs/images/undo-UG/after_delete_1.png
  docs/images/undo-UG/after_delete_undo.png
  docs/images/undo-UG/after_delete_undo_scrolled_down.png
  docs/images/undo-UG/after_edit_1.png
  docs/images/undo-UG/after_edit_undo.png
  docs/images/undo-UG/one_contact_GUI.png
  docs/images/undo-UG/undo_fail.png
  docs/images/undo-UG/undo_successful.png
  docs/img.png
  docs/img_1.png
Labels: documentation

#81 Update UG for edit and sort function
  docs/UserGuide.md
  docs/images/edit-UG/editfailureinvalid.png
  docs/images/edit-UG/editfailuremissing.png
  docs/images/edit-UG/editfailuremultiple.png
  docs/images/edit-UG/editformat.png
  docs/images/edit-UG/editresult.png
  docs/images/editformat.png
  docs/images/editresult.png
  docs/images/sort-UG/sortfailuremissing.png
  docs/images/sort-UG/sortformat.png
  docs/images/sort-UG/sortresult.png
Labels: documentation

#87 Update CloneCommand Bug
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CloneCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, enhancement

#105 Enhance delete by adding functionality to delete multiple
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement

#108 Update UiManager to correct theme
  src/main/java/seedu/address/ui/UiManager.java
Labels: bug

#110 Unified find feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UFindCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UFindCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UFindCommandParserTest.java
Labels: enhancement, priority.High

#109 Add calendar window
  build.gradle
  src/main/java/seedu/address/commons/util/CalendarUtil.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/images/calendar2.png
  src/main/resources/view/CalendarWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#113 Fix clone bug
  src/main/java/seedu/address/logic/commands/CloneCommand.java
  src/test/java/seedu/address/logic/commands/CloneCommandTest.java
Labels: bug

#114 Fix DeleteCommand bug where index must be in order
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: bug
